language: cpp
git:
  quiet: true
  submodules: true
  depth: 3
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          packages:
            - libboost-all-dev
            - libopencv-dev

before_install:
  - eval "${MATRIX_EVAL}"

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage .. 
     - make -j$(nproc)

notifications:
  email: false
